services:
  jeux-malo-bot:
    build: 
      context: .
    container_name: arcade_bot
    env_file:
      - .env
    networks:
      - arcade_bot_network

  mongodb:
    image: mongo:latest
    container_name: arcade_bot_mongo
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    networks:
      - arcade_bot_network

networks:
  arcade_bot_network:

volumes:
  mongodb_data: